loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: gp2
    size: 40Gi

promtail:
  enabled: true
  tolerations:
    - key: reserved-pool
      operator: Equal
      value: "true"
      effect: NoSchedule
  nodeSelector:
    purpose: workflow-jobs

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 8.1.6

