apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-artifact-gcs-
  namespace: argo
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 8737 #; any non-root user
    fsGroup: 8737
  serviceAccountName: argo
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
  entrypoint: output-artifact-gcs-example
  arguments:
    parameters:
      - name: message
        value: hello argo
  templates:
    - name: output-artifact-gcs-example
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
        artifacts:
          - name: my-art
            path: /my-artifact
            gcs:
              bucket: bowerbird-testing-home
              key: bowerbird
      container:
        image: debian:latest
        command: [sh, -c]
        args: ["sleep 1; echo -n {{inputs.parameters.message}} > /mnt/vol/hello_world.txt"]
#        args: ["sleep 1; ls -la"]
        volumeMounts:
        - name: workdir
          mountPath: /mnt/vol  
      outputs:
        artifacts:
          - name: out-art
            path: /mnt/vol/hello_world.txt
            archive:
              none: {}
            gcs:
              bucket: bowerbird-testing-home
              key: bowerbird/hello_world.txt
