apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: singlem-aws-
  namespace: argo
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 8737 #; any non-root user
    fsGroup: 8737
  serviceAccountName: argo
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 13Gi
  entrypoint: output-artifact-gcs-example
  ttlStrategy:
    secondsAfterCompletion: 3600 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 3600     # Time to live after workflow is successful
    secondsAfterFailure: 3600   # Time to live after workflow fails
  arguments:
    parameters:
      - name: SRA_accession_num
        value: ERR2535307
  templates:
    - name: output-artifact-gcs-example
      inputs:
        parameters:
          - name: SRA_accession_num
            value: '{{workflow.parameters.SRA_accession_num}}'
        artifacts:
          - name: my-art
            path: /my-artifact
            # gcs:
            #   bucket: bowerbird-testing-home
            #   key: bowerbird
            s3:
              endpoint: s3.amazonaws.com
              bucket: batch-artifact-repository-401305384268
              key: test
      container:
        name: singlem
        image: gcr.io/maximal-dynamo-308105/singlem:0.13.2-dev31.e97d171
        env:
        - name: TMPDIR
          value: /mnt/vol
        command: [bash,-c]
        args: ["
        cd /mnt/vol;
        kingfisher 
        get  
        -r {{inputs.parameters.SRA_accession_num}} 
        --output-format-possibilities sra
        --guess-aws-location
        --hide-download-progress
        -m 'aws-http'
        &&
        ls
        && 
        /tmp/singlem/bin/singlem pipe
          --sra-files {{inputs.parameters.SRA_accession_num}}.sra
          --archive_otu_table >(gzip >{{inputs.parameters.SRA_accession_num}}.annotated.singlem.json.gz)
          --threads 1
          --singlem-metapackage /mpkg
        &&
        ls /mnt/vol
        "]
        volumeMounts:
        - name: workdir
          mountPath: /mnt/vol  
        resources:
          requests:
            memory: "3600Mi"
            cpu: 1
      # nodeSelector:
      #   purpose: workflow-jobs
      tolerations:
      - key: "reserved-pool"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      outputs:
        artifacts:
          - name: out-art
            path: '/mnt/vol/{{workflow.parameters.SRA_accession_num}}.annotated.singlem.json.gz'
            s3:
              endpoint: s3.amazonaws.com
              bucket: batch-artifact-repository-401305384268
              key: 'test/{{workflow.parameters.SRA_accession_num}}.annotated.singlem.json.gz'
            # gcs:
            #   bucket: bowerbird-testing-home
            #   key: 'bowerbird/{{workflow.parameters.SRA_accession_num}}.unannotated.singlem.json.gz'
