apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: s3-flow
  namespace: argo
spec:
  match:
    - select: 
        labels:
          log: 'yes' 
  localOutputRefs:
    - s3-output
    - loki-output
