apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-simple
  namespace: logging
spec:
  fluentd: {}
  fluentbit:
    tolerations:
      - key: reserved-pool
        operator: Equal
        value: "true"
        effect: NoSchedule
  controlNamespace: logging
