apiVersion: v1 
kind: ConfigMap
metadata:   
  name: workflow-controller-configmap
data:   
  containerRuntimeExecutor: pns
  workflowDefaults: |
    spec:  
      podMetadata:
        labels:
          log: 'yes'
