apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: singlem-
  namespace: argo
  labels:
    nickname: argo-first-batch
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 8737
    fsGroup: 8737
  serviceAccountName: argo
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10556Mi
  entrypoint: singlem-task
  ttlStrategy:
    secondsAfterCompletion: 3600
    secondsAfterSuccess: 7200
    secondsAfterFailure: 10800
  arguments:
    parameters:
      - name: SRA_accession_num
        value: ERR4374862
  templates:
    - name: singlem-task
      retryStrategy:
        limit: "2"
        retryPolicy: Always
      inputs:
        parameters:
          - name: SRA_accession_num
            value: ERR4374862
      archiveLocation:
        archiveLogs: true
        s3:
          endpoint: s3.amazonaws.com
          bucket: batch-artifact-repository-401305384268
          key: test6/{{workflow.name}}-{{workflow.parameters.SRA_accession_num}}
      container:
        name: singlem
        image: gcr.io/maximal-dynamo-308105/singlem:0.13.2-dev32.e97d171
        env:
          - name: TMPDIR
            value: /mnt/vol
        command:
          - bash
          - -c
        args:
          - "\techo Processing {{workflow.name}} {{inputs.parameters.SRA_accession_num}};\n\tcd /mnt/vol;\n\tkingfisher get -r {{inputs.parameters.SRA_accession_num}} --output-format-possibilities sra --guess-aws-location --hide-download-progress -m 'aws-http' &&\n\tls -l && \n\tpidstat -r 5 -e bash -c '/tmp/singlem/bin/singlem pipe --sra-files {{inputs.parameters.SRA_accession_num}}.sra --archive_otu_table >(gzip >{{inputs.parameters.SRA_accession_num}}.annotated.singlem.json.gz) --threads 1 --singlem-metapackage /mpkg' |awk '{print $7}' |sort -rn |head -1 >max_rss"
        volumeMounts:
          - name: workdir
            mountPath: /mnt/vol
        resources:
          requests:
            memory: 512Mi
            cpu: 750m
      nodeSelector:
        purpose: workflow-jobs
      tolerations:
        - key: reserved-pool
          operator: Equal
          value: "true"
          effect: NoSchedule
      outputs:
        artifacts:
          - name: out-art
            path: /mnt/vol/{{workflow.parameters.SRA_accession_num}}.annotated.singlem.json.gz
            s3:
              endpoint: s3.amazonaws.com
              bucket: batch-artifact-repository-401305384268
              key: test6/{{workflow.name}}-{{workflow.parameters.SRA_accession_num}}/{{workflow.parameters.SRA_accession_num}}.annotated.singlem.json.gz
            archive:
              none: {}
          - name: out-art2
            path: /mnt/vol/max_rss
            s3:
              endpoint: s3.amazonaws.com
              bucket: batch-artifact-repository-401305384268
              key: test6/{{workflow.name}}-{{workflow.parameters.SRA_accession_num}}/max_rss
            archive:
              none: {}
